# Generated by Django 2.0.4 on 2018-05-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_league_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='teams',
        ),
    ]
