# Generated by Django 2.0.4 on 2018-05-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_remove_league_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='teams',
            field=models.ManyToManyField(to='leagues.Squad'),
        ),
    ]
